### ISSUE TITLE
Mod Codebase and or Animations has been stolen and posted on CurseForge under a Different Mod Name(?)

### ISSUE THREAD

**Issue by XanderCreates** [Trainguy9512/trainguys-animation-overhaul#102]
Evidence; Player Animation Files.. Identical File Sizes + Names, likely a few removed, but they appear the same.
![image](https://user-images.githubusercontent.com/69139978/215301413-6e9fae5c-be65-4afc-a35b-252f43a63e85.png)

Perps
![image](https://user-images.githubusercontent.com/69139978/215301439-a473eca8-3309-4bd4-91da-791cff9eccf6.png)

Mod Link + Repo
https://www.curseforge.com/minecraft/mc-mods/improved-animations
https://github.com/MincraftEinstein/ImprovedAnimations

**Comment by XanderCreates** [comment]
Did you give them permission?

**Comment by EysseW** [comment]
Can confirm. I confronted the owner of the mod in question a while back about the issue, to which he changed my bug report to "Done!" and deleted any additional messages about the issue. I then tried to inform others in different issues. He deleted every single of these comments as well... The worst part is, this is straight up illegal. Unlike most minecraft mods, Trainguys Animation Overhaul is not licensed under a free license.

**Comment by Patcybermind** [comment]
they have a discord server yall can just go there and spam something like 
is it true that this is just a copy of this way more popular project? https://github.com/Trainguy9512/trainguys-animation-overhaul

**Comment by Patcybermind** [comment]
https://support.github.com/contact/report-abuse?category=report-content&report=other&report_type=unspecified

**Comment by Patcybermind** [comment]
someone can report them here
i don't know if i legally can

**Comment by EysseW** [comment]
I already did

**Comment by Kelvin285** [comment]
I've been talking to Trainguy as well to try and get the issue resolved.
I was tricked into helping DrAlpha fix a few bugs in a GitHub repo while I was making a mod for him for a Fiverr commission, and was told that he had permission to port the mod to 1.19.3.  When I checked the license it said Creative Commons, so I assumed it was fine, but once I found out DrAlpha wasn't actually given any permissions and released the mod on CurseForge with himself as the "mascot" of the mod, I blocked him and informed Trainguy of the entire situation.  My lack of awareness about what was going on is unfortunately what probably kept this going for as long as it did.
Hopefully the mod gets taken off of Curseforge soon, as I personally don't have any way to get rid of it myself.  I have however submitted a report about the mod being stolen to Curseforge.  I didn't know about the GitHub reporting feature, but since you've posted a link to it I'll try to see if I can help with getting the stolen GitHub repo taken down as well.

**Comment by Trainguy9512** [comment]
i confronted dralpha about this yesterday about the license violation in the 1.18.x-architectury branch. i submitted a ticket to curseforge, so hopefully it gets taken down from there pretty soon. as far as i'm concerned dralpha is the main person responsible for this as unfortunately ive talked to numerous people now who have had poor experiences with this person being manipulative- but hopefully this instance is taken care of soon

**Comment by HarperTL** [comment]
i have just found this mod posted by the same people on 9minecraft, image is for the people they credited on the actual mod in game and here's the link to the website: https://www.9minecraft.net/improved-animations-mod/
![trainguys mod](https://user-images.githubusercontent.com/123916034/215928709-7c7bfe7b-066e-4157-a406-0de423a1e291.JPG)

**Comment by Trainguy9512** [comment]
been taken down on curseforge, not sure if it was because of my ticket or they did it themselves- regardless, taken care of
