### ISSUE TITLE
fresh animations compatibility

### ISSUE THREAD

**Issue by souls-are-tasty** [Trainguy9512/trainguys-animation-overhaul#43]
please can you make this compatible with fresh animations' eye movement since the walk cycle and arm movement work but not eye and eyebrow movement

**Comment by kingarthur0975** [comment]
Fresh Animations does not effect player animations, including eye movement. Whether or not the mod creator decides to add in eye movement is not related to that resource pack. Additionally, adding eye/facial animations into the mod would be a huge pain in the ass because of the different face proportions of different skins.

**Comment by souls-are-tasty** [comment]
I meant for the mobs but Dw I got that fixed
